CREATE TRIGGER UPDATE_MONEY ON PHIEU_THU
FOR INSERT 
AS 
DECLARE @TIEN FLOAT 
SELECT @TIEN = SOTIEN FROM INSERTED
UPDATE PHIEU_XUAT SET SoTienDaTra = PHIEU_XUAT.SoTienDaTra + @TIEN
FROM INSERTED WHERE PHIEU_XUAT.SOPX = INSERTED.SOPX 

DROP TRIGGER UPDATE_MONEY
--INSERT PHIEU_THU VALUES('CT8', '2022-10-10', 18000, N'PHU E ACH', 'PX2')

CREATE PROC PHIEUTHUFULL(@MACT NCHAR(10)) AS 
SELECT TenKHG, DiaChiKHG, DienGiai, SoTien, PHIEU_XUAT.SoPX, SoCT, NgayCT 
FROM PHIEU_THU INNER JOIN PHIEU_XUAT ON PHIEU_XUAT.SoPX = PHIEU_THU.SoPX
INNER JOIN KHACH_HANG ON KHACH_HANG.MaKHG = PHIEU_XUAT.MaKHG WHERE PHIEU_THU.SoCT = @MACT

EXEC PHIEUTHUFULL 'CT1'